config/routes.rb
Rails.application.routes.draw do


  root 'demo#index'
  get 'demo/index'
  get 'demo/index'
  get 'demo/hello'
  get 'demo/about'
  get 'demo/contact_us'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'
  # get 'test/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #Default routes
  # get ':controller(/:action(/:id))'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end

  def hello
    #redirect_to(:controller => 'demo', :action => 'index')
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params[:page]
  end

  def about
    render('about')
  end

  def contact_us
    if ['us', 'ca'].include?(params[:country])
      @phone = '(800) 555-6789'
    elsif params[:country] == 'uk'
      @phone = '(020) 123-2222'
    elsif params[:country] == 'in'
      @phone = '(+91) 9712342345'
    else
      @phone = '+1 (987) 654-3210'
    end
    render('contact_us')
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = Subject.order('position ASC')
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      # Succeeds
      redirect_to(subjects_path)
    else
      # Failed
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    redirect_to(subjects_path)
  end

  private
   def subject_params
     params.require(:subject).permit(:name, :visible, :position)
   end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object  })
  end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
<div id="error-explanation">
  <h2><%= pluralize(object.error.size, "error") %> prohibited this record from being saved</h2>
  <p> There are problems with following fields: </p>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li> <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/demo/about.html.erb
<h1>About us</h1>
<h3>Just started linking pages and parameters here in Ruby on Rails</h3>
<br/>
<br/>

<p><%= link_to('Contact us', {:action => 'contact_us', :country => 'us'}) %> </p>
<br/>

app/views/demo/contact_us.html.erb
<h1>Contact us here</h1>
<p> In case of any issue, please reach us here </p> <br/>

<p>Phone: <%= @phone %></p>

<a href="/demo/about"> About Us </a>

app/views/demo/hello.html.erb
<h1>This is Hello controller page :D </h1>

<%= 1 + 1 %>
</br>

<% target = 'world' %>
<%="Hello #{target}!" %>

<% @array.each do |n| %>
<p> <%= n %> </p>
<%end %>
<br/>
<%=link_to("Index Page", {:action => 'index'}) %>
<br/>

ID: <%= @id %> <br/>
ID: <%= params[:id] %><br/>
Page: <%= @page %> <br/>
Next Page: <%=@page.to_i + 1 %><br/>

app/views/demo/index.html.erb
<h1>Welcome to Ruby on Rails!</h1>
<a href="/demo/hello"> Hello Page 1</a> </br>
<%= link_to("Hello Page 2", {:action => 'hello'}) %>
<br/>

<%= link_to("Hello with parameters", {:action => 'hello', :page => 5, :id => 20}) %><br/>

<%= link_to('All Subjects', subjects_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/subjects/_form.html.erb
<% error_messages_for(f.object) %>
<table summary="Subject form fields">
  <tr>
    <th> Name </th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th> Position </th>
    <td><%= f.text_field(:position) %></td>
  </tr>
  <tr>
    <th> Visible </th>
    <td><%= f.text_field(:visible) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>
<div class="subjects delete">
  <h2>Delete Subject</h2>
  <%= form_for(@subject, :method => 'delete') do |f| %>
    <p> Are you sure you want to permanently delete the subject?</p>
    <p><%= @subject.name %></p>
    <div class="form-buttons">
    <%= f.submit("Delete Subject") %>
  </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>
<div class="subjects edit">
  <h2>Update Subject</h2>
  <%= form_for(@subject) do |f| %>
     <%= render(:partial => 'form', :locals => {:f => f}) %>

  <div class="form-buttons">
    <%= f.submit("Update Subject") %>
  </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject List">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%=subject.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%=subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>
<div class="subjects new">
  <h2>Create Subject</h2>
  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
  <div class="form-buttons">
    <%= f.submit("Create Subject") %>
  </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<h1>Subjects#show</h1>
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>
  <table summary="Subject Detailed View">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %> </td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>
</div>